"$schema" = 'https://starship.rs/config-schema.json'

format = """
[▓](fg:#ffffff bg:#ffffff)\
[](bg:#c73d3d fg:#ffffff)\
$directory\
[](fg:#c73d3d bg:#4a1f1f)\
$git_branch\
$git_status\
[](fg:#4a1f1f)\
\n$character"""

right_format = """$cmd_duration"""


[directory]
style = "fg:#e3e5e5 bg:#c73d3d"
format = "[ $path ]($style)"
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4a1f1f"
format = '[[ $symbol $branch ](fg:#f0d0d0 bg:#4a1f1f)]($style)'

[git_status]
style = "bg:#4a1f1f"
format = '[[($all_status$ahead_behind )](fg:#f0d0d0 bg:#4a1f1f)]($style)'

# コマンド実行時間
[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"